const express =  require('express')
const router = express.Router() ;
const {authMiddleware,isAdmin} = require('../middlewares/authMiddleware')
const {verifiedAccount , loginAdmin ,  resetPassword , forgotPasswordToken , updatePassword , logout , createUser , handleRefreshToken , unBlockUser , blockUser, login ,getAllUsers , getOneUser , deleteUser ,updateUser, sendVerificationLink} = require('../controller/userController') 
router.post('/signup'  , createUser)
router.post('/login',login)
router.post('/loginadmin', loginAdmin )
router.post('/forgot-password', forgotPasswordToken )
router.patch('/password/:id',updatePassword)
router.put('/reset-password/:token', resetPassword )
router.get('/all-users' ,getAllUsers)
router.get('/one-user/:id',getOneUser)
router.get('/refresh',handleRefreshToken)
router.get('/logout' , logout )
router.delete('/delete-user/:id',deleteUser)
router.put('/update-user/:id', updateUser)
router.put('/block-user/:id',authMiddleware , isAdmin , blockUser)
router.put('/unblock-user/:id',  unBlockUser)
router.post('/verification/:id',  sendVerificationLink)
router.get('/verifiedAccount/:token',verifiedAccount)
  module.exports = router ; 